// versions/04-react-hooks/src/components/SearchResultAlbum.jsx
import { useState } from 'react';
import clsx from 'clsx';
import { useAlbumList, MAX_LIST_SIZE } from '../store/AlbumListContext';

export function SearchResultAlbum({ album }) {
  const [active, setActive] = useState(false);
  const { addAlbum, topAlbumList } = useAlbumList();
  const isFull = topAlbumList.length >= MAX_LIST_SIZE;

  return (
    <div className="flex-item">
      <div className={clsx('album-slide', active && 'active')} onClick={() => setActive(true)}>
        <img className="album-image" alt={album.name} src={album.image} />
        <div className="album-info overlay">
          <button
            type="button"
            className="close-button"
            aria-label="Close album details"
            onClick={(e) => {
              e.stopPropagation();
              setActive(false);
            }}
          >
            <span className="icon close-content" />
          </button>
          <div className="album-info-box">
            <h4>{album.name}</h4>
            <p className="artist">{album.artist}</p>
            <button
              type="button"
              className="add-to-list button button-secondary"
              disabled={isFull}
              onClick={(e) => {
                e.stopPropagation();
                addAlbum(album);
              }}
            >
              {isFull ? 'List Full' : 'Add To List'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// versions/07-vue/src/components/SearchResultAlbum.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useAlbumStore, MAX_LIST_SIZE } from '../store/useAlbumStore';
import type { Album } from '../types';

const props = defineProps<{ album: Album }>();

const store = useAlbumStore();
const active = ref(false);
const isFull = computed(() => store.topAlbumList.length >= MAX_LIST_SIZE);

function close(): void {
  active.value = false;
}

function add(): void {
  store.addAlbum(props.album);
}
</script>

<template>
  <div class="flex-item">
    <div class="album-slide" :class="{ active }" @click="active = true">
      <img class="album-image" :alt="album.name" :src="album.image" />
      <div class="album-info overlay">
        <button
          type="button"
          class="close-button"
          aria-label="Close album details"
          @click.stop="close"
        >
          <span class="icon close-content"></span>
        </button>
        <div class="album-info-box">
          <h4>{{ album.name }}</h4>
          <p class="artist">{{ album.artist }}</p>
          <button
            type="button"
            class="add-to-list button button-secondary"
            :disabled="isFull"
            @click.stop="add"
          >
            {{ isFull ? 'List Full' : 'Add To List' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
