// versions/06-svelte/src/components/SearchResults.svelte
<script lang="ts">
  import type { AlbumSearch } from '../lib/search.svelte';
  import { albumList } from '../lib/albums.svelte';
  import SearchResultAlbum from './SearchResultAlbum.svelte';

  let { search }: { search: AlbumSearch } = $props();

  // Albums already on the Top 10 list drop out of the results, matching vanilla.
  const visible = $derived(search.results.filter((a) => !albumList.has(a.id)));
</script>

<section id="searchResults" class="album-search-results">
  {#if search.loading}
    <span class="loading"><span class="loader"></span></span>
  {:else if search.error}
    <p class="alert">{search.error}</p>
  {:else if search.searched && search.results.length === 0}
    <p class="alert">No results were found. Please try another search</p>
  {:else}
    {#each visible as album (album.id)}
      <SearchResultAlbum {album} />
    {/each}
  {/if}
</section>

// versions/04-react-hooks/src/components/SearchResults.jsx
import { useMemo } from 'react';
import { useAlbumSearch } from '../hooks/useAlbumSearch';
import { useAlbumList } from '../store/AlbumListContext';
import { SearchResultAlbum } from './SearchResultAlbum';

export function SearchResults({ term }) {
  const { albums, loading, error } = useAlbumSearch(term);
  const { topAlbumList } = useAlbumList();

  const listedIds = useMemo(() => new Set(topAlbumList.map((a) => a.id)), [topAlbumList]);
  const visible = useMemo(
    () => albums.filter((a) => !listedIds.has(a.id)),
    [albums, listedIds],
  );

  return (
    <section id="searchResults" className="album-search-results">
      {loading && (
        <span className="loading">
          <span className="loader" />
        </span>
      )}

      {error && <p className="alert">{error.message}</p>}

      {!loading && !error && term && albums.length === 0 && (
        <p className="alert">No results were found. Please try another search</p>
      )}

      {visible.map((album) => (
        <SearchResultAlbum key={album.id} album={album} />
      ))}
    </section>
  );
}
