// versions/07-vue/src/components/SearchResults.vue
<script setup lang="ts">
import { computed } from 'vue';
import { storeToRefs } from 'pinia';
import { useAlbumStore } from '../store/useAlbumStore';
import type { Album } from '../types';
import SearchResultAlbum from './SearchResultAlbum.vue';

const props = defineProps<{
  albums: Album[];
  loading: boolean;
  error: string | null;
  hasSearched: boolean;
}>();

const store = useAlbumStore();
const { topAlbumList } = storeToRefs(store);

const listedIds = computed(() => new Set(topAlbumList.value.map((a) => a.id)));
const visible = computed(() => props.albums.filter((a) => !listedIds.value.has(a.id)));
const noResults = computed(
  () => props.hasSearched && !props.loading && !props.error && props.albums.length === 0,
);
</script>

<template>
  <section id="searchResults" class="album-search-results">
    <span v-if="loading" class="loading">
      <span class="loader"></span>
    </span>

    <p v-else-if="error" class="alert">{{ error }}</p>

    <p v-else-if="noResults" class="alert">
      No results were found. Please try another search
    </p>

    <SearchResultAlbum v-for="album in visible" :key="album.id" :album="album" />
  </section>
</template>

// versions/03-react-classes/src/components/SearchResults.jsx
import React from 'react';
import PropTypes from 'prop-types';
import SearchResultAlbum from './SearchResultAlbum';
import { albumShape } from './albumShape';

export default class SearchResults extends React.Component {
  render() {
    const { results, loading, error, hasSearched, listedIds, isFull, onAdd } = this.props;
    const visible = results.filter((a) => !listedIds.has(a.id));

    return (
      <section id="searchResults" className="album-search-results">
        {loading && (
          <span className="loading">
            <span className="loader" />
          </span>
        )}

        {!loading && error && <p className="alert">{error}</p>}

        {!loading && !error && hasSearched && results.length === 0 && (
          <p className="alert">No results were found. Please try another search</p>
        )}

        {!loading &&
          !error &&
          visible.map((album) => (
            <SearchResultAlbum key={album.id} album={album} isFull={isFull} onAdd={onAdd} />
          ))}
      </section>
    );
  }
}

SearchResults.propTypes = {
  results: PropTypes.arrayOf(albumShape).isRequired,
  loading: PropTypes.bool.isRequired,
  error: PropTypes.string,
  hasSearched: PropTypes.bool.isRequired,
  listedIds: PropTypes.instanceOf(Set).isRequired,
  isFull: PropTypes.bool.isRequired,
  onAdd: PropTypes.func.isRequired,
};

SearchResults.defaultProps = {
  error: null,
};
