// versions/07-vue/src/components/SearchResults.vue
<script setup lang="ts">
import { computed } from 'vue';
import { storeToRefs } from 'pinia';
import { useAlbumStore } from '../store/useAlbumStore';
import type { Album } from '../types';
import SearchResultAlbum from './SearchResultAlbum.vue';

const props = defineProps<{
  albums: Album[];
  loading: boolean;
  error: string | null;
  hasSearched: boolean;
}>();

const store = useAlbumStore();
const { topAlbumList } = storeToRefs(store);

const listedIds = computed(() => new Set(topAlbumList.value.map((a) => a.id)));
const visible = computed(() => props.albums.filter((a) => !listedIds.value.has(a.id)));
const noResults = computed(
  () => props.hasSearched && !props.loading && !props.error && props.albums.length === 0,
);
</script>

<template>
  <section id="searchResults" class="album-search-results">
    <span v-if="loading" class="loading">
      <span class="loader"></span>
    </span>

    <p v-else-if="error" class="alert">{{ error }}</p>

    <p v-else-if="noResults" class="alert">
      No results were found. Please try another search
    </p>

    <SearchResultAlbum v-for="album in visible" :key="album.id" :album="album" />
  </section>
</template>

// versions/05-react-modern/src/components/SearchResults.tsx
import { useMemo } from 'react';
import { useAlbumSearch } from '../hooks/useAlbumSearch';
import { useAlbumStore } from '../store/useAlbumStore';
import { SearchResultAlbum } from './SearchResultAlbum';

interface SearchResultsProps {
  term: string;
}

export function SearchResults({ term }: SearchResultsProps) {
  const { data, isFetching, isError, error } = useAlbumSearch(term);
  const topAlbumList = useAlbumStore((s) => s.topAlbumList);

  const listedIds = useMemo(() => new Set(topAlbumList.map((a) => a.id)), [topAlbumList]);
  const visible = (data ?? []).filter((a) => !listedIds.has(a.id));

  return (
    <section id="searchResults" className="album-search-results">
      {isFetching && (
        <span className="loading">
          <span className="loader" />
        </span>
      )}

      {isError && <p className="alert">{(error as Error).message}</p>}

      {!isFetching && !isError && data?.length === 0 && (
        <p className="alert">No results were found. Please try another search</p>
      )}

      {visible.map((album) => (
        <SearchResultAlbum key={album.id} album={album} />
      ))}
    </section>
  );
}
